name: Build and Push image to DockerHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sharmila231/my-iamge:v1
    - name: Push the Docker image
      run: docker push sharmila231/my-iamge:v1
